# Generated by Django 4.2.5 on 2023-11-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_user', models.CharField(default='User_<built-in function id>', max_length=100)),
                ('ratings', models.IntegerField(choices=[(0, 'WORST'), (1, 'VERY BAD'), (2, 'BAD'), (3, 'AVERAGE'), (4, 'GOOD'), (5, 'EXCELLENT')], default=3)),
                ('review_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
    ]
