# Generated by Django 4.2.5 on 2023-11-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_publishDate',
            new_name='product_publish_date',
        ),
    ]
