# Generated by Django 4.2.5 on 2023-11-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_review_review_review_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='Shop/Product/images'),
        ),
    ]
