# Generated by Django 4.2.5 on 2023-11-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_product_publishdate_product_product_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_publish_date',
            new_name='product_publishDate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sub_category',
            new_name='product_subCategory',
        ),
    ]
