# Generated by Django 4.2.5 on 2023-11-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.ImageField(default='', upload_to='Shop/images/reviews'),
        ),
    ]
