# Generated by Django 4.2.5 on 2023-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_review_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=14)),
                ('pic', models.ImageField(upload_to='Shop/images/contact/')),
                ('query', models.CharField(max_length=1000)),
                ('getUpdates', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
            ],
        ),
    ]
