# Generated by Django 4.2.5 on 2023-11-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
